server:
  port: 8088

spring:
  application:
    name: migration.test.demo
  profiles:
    active: default
migration:
  config-center-url: ""
  diff-service-url: ""
  default-timeout: 5000

logging:
  level:
    top.bulgat: DEBUG
