services:
  migration.admin.api:
    build:
      context: ../migration-admin/migration-admin-api
      dockerfile: Dockerfile
    image: hbulgat/migration.admin.api:latest
    container_name: migration.admin.api
    env_file:
      - .env
    ports:
      - "8090:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - MIGRATION_NACOS_SERVER_ADDR=${MIGRATION_NACOS_SERVER_ADDR}
      - MIGRATION_NACOS_NAMESPACE=${MIGRATION_NACOS_NAMESPACE}
      - MIGRATION_NACOS_USERNAME=${MIGRATION_NACOS_USERNAME}
      - MIGRATION_NACOS_PASSWORD=${MIGRATION_NACOS_PASSWORD}
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - LOGGING_FILE_PATH=/app/logs/migration.admin.api
    volumes:
      - /var/log/myapp/migration.admin.api:/app/logs/migration.admin.api
    restart: always

  migration.diff.service:
    build:
      context: ../migration-diff-service
      dockerfile: Dockerfile
    image: hbulgat/migration.diff.service:latest
    container_name: migration.diff.service
    env_file:
      - .env
    ports:
      - "8091:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - MIGRATION_NACOS_SERVER_ADDR=${MIGRATION_NACOS_SERVER_ADDR}
      - MIGRATION_NACOS_NAMESPACE=${MIGRATION_NACOS_NAMESPACE}
      - MIGRATION_NACOS_USERNAME=${MIGRATION_NACOS_USERNAME}
      - MIGRATION_NACOS_PASSWORD=${MIGRATION_NACOS_PASSWORD}
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - LOGGING_FILE_PATH=/app/logs/migration.diff.service
    volumes:
      - /var/log/myapp/migration.diff.service:/app/logs/migration.diff.service
    restart: always

  migration.admin.ui:
    build:
      context: ../migration-admin/migration-admin-ui
      dockerfile: Dockerfile
    image: hbulgat/migration.admin.ui:latest
    container_name: migration.admin.ui
    ports:
      - "8088:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: always
    depends_on:
      - migration.admin.api
