server:
  port: 8080

spring:
  application:
    name: migration.admin.api
  profiles:
    active: local

migration:
  admin:
    internal-token: "MIGRATION_DEFAULT_SDK_TOKEN"

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
