server:
  port: 8081

spring:
  application:
    name: migration.diff.service
  profiles:
    active: local

migration:
  diff:
    internal-token: "MIGRATION_DEFAULT_SDK_TOKEN"

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
