server:
  port: 8081

spring:
  datasource:
    url: ${MIGRATION_DB_URL:jdbc:mysql://localhost:3306/migration?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8}
    username: ${MIGRATION_DB_USERNAME:}
    password: ${MIGRATION_DB_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver

#migration:
#  nacos:
#    server-addr:
#    namespace: ${MIGRATION_NACOS_NAMESPACE:}
#    username: ${MIGRATION_NACOS_USERNAME:}
#    password: ${MIGRATION_NACOS_PASSWORD:}
migration-diff:
  auth:
    internal-token: ${DIFF_INTERNAL_TOKEN}
  config-center:
    type: nacos
    server-addr: ${MIGRATION_NACOS_SERVER_ADDR:}
    username: nacos
    password: nacos
    meta-info:
      namespace: namespace

logging:
  level:
    top.bulgat: INFO
