server:
  port: 8081

spring:
  datasource:
    url: ${MIGRATION_DB_URL:jdbc:mysql://localhost:3306/migration?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8}
    username: ${MIGRATION_DB_USERNAME:}
    password: ${MIGRATION_DB_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver

migration:
  diff:
    internal-token: ${MIGRATION_DIFF_INTERNAL_TOKEN}
  nacos:
    server-addr: ${MIGRATION_NACOS_SERVER_ADDR:}
    namespace: ${MIGRATION_NACOS_NAMESPACE:}
    username: ${MIGRATION_NACOS_USERNAME:}
    password: ${MIGRATION_NACOS_PASSWORD:}

logging:
  level:
    top.bulgat: INFO
