server:
  port: 8081

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/migration?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8}
    username: ${SPRING_DATASOURCE_USERNAME:}
    password: ${SPRING_DATASOURCE_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver

migration-diff:
  auth:
    internal-token: ${MIGRATION_DIFF_AUTH_INTERNAL_TOKEN}
  config-center:
    type: nacos
    server-addr: ${MIGRATION_DIFF_CONFIG_CENTER_SERVER_ADDR}
    username: ${MIGRATION_DIFF_CONFIG_CENTER_USERNAME}
    password: ${MIGRATION_DIFF_CONFIG_CENTER_PASSWORD}
    meta-info:
      namespace: ${MIGRATION_DIFF_CONFIG_CENTER_META_INFO_NAMESPACE:}
  notice:
    email:
      auth: true
      charset: UTF-8
      ssl-enable: true
      host: ""
      port: 1
      username: ""
      password:
logging:
  level:
    top.bulgat: INFO
